#!/usr/bin/env python3
"""Compile all hacks/glx/*.c, build symbol def/use maps, and compute the
support-source closure for each candidate GL hack. Emits a CMake include."""
import json, os, re, subprocess, sys, tempfile
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLX = f"{ROOT}/third_party/xscreensaver/hacks/glx"
OBJ = os.path.join(tempfile.gettempdir(), "xss_globjs")
os.makedirs(OBJ, exist_ok=True)

cc = json.load(open(f"{ROOT}/build/compile_commands.json"))
cmd = next(e["command"] for e in cc if e["file"].endswith("glx/gears.c"))
# strip the -o/-c tail
base = cmd.split(" -o ")[0].split()

CANDIDATES = sys.argv[1].split(",")

sources = sorted(f for f in os.listdir(GLX) if f.endswith(".c"))
fails = {}

def compile_one(f):
    o = f"{OBJ}/{f[:-2]}.o"
    if os.path.exists(o):
        return f, True, ""
    r = subprocess.run(base + ["-w", "-o", o, "-c", f"{GLX}/{f}"],
                       capture_output=True, text=True)
    return f, r.returncode == 0, r.stderr.strip().splitlines()[-1] if r.stderr else ""

with ThreadPoolExecutor(10) as ex:
    for f, ok, err in ex.map(compile_one, sources):
        if not ok:
            fails[f[:-2]] = err

# symbol maps from nm
defs, uses = {}, {}     # name -> set(symbols)
for f in sources:
    n = f[:-2]
    if n in fails: continue
    out = subprocess.run(["nm", "-g", f"{OBJ}/{n}.o"], capture_output=True,
                         text=True).stdout
    d, u = set(), set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 2: continue
        typ, sym = parts[-2], parts[-1]
        (u if typ == "U" else d).add(sym)
    defs[n], uses[n] = d, u

# module files (never pulled in as a dependency of another hack)
modules = set()
for f in sources:
    if "XSCREENSAVER_MODULE" in open(f"{GLX}/{f}", errors="replace").read():
        modules.add(f[:-2])

sym2src = {}
for n, d in defs.items():
    if n in modules: continue          # support files only
    for s in d:
        sym2src.setdefault(s, n)

result, blocked = {}, {}
for hack in CANDIDATES:
    if hack in fails:
        blocked[hack] = f"does not compile: {fails[hack]}"
        continue
    closure, todo, missing = set(), set(uses.get(hack, set())), set()
    seen_syms = set()
    while todo:
        s = todo.pop()
        if s in seen_syms: continue
        seen_syms.add(s)
        src = sym2src.get(s)
        if src is None or src in closure or src == hack:
            continue
        if src in fails:
            missing.add(src)
            continue
        closure.add(src)
        todo |= uses[src]
    if missing:
        blocked[hack] = "needs non-compiling: " + " ".join(sorted(missing))
    else:
        result[hack] = sorted(closure)

print("# batch2-glhacks.cmake -- GENERATED by scripts/gen_glhack_deps.py")
print("# (symbol-closure over hacks/glx objects; do not hand-edit lists)")
for hack in sorted(result):
    extras = " ".join(result[hack])
    print(f"xss_add_glhack({hack} {extras})" if extras
          else f"xss_add_glhack({hack})")
print()
for hack in sorted(blocked):
    print(f"# BLOCKED {hack}: {blocked[hack]}")
print(f"\n# {len(result)} generated, {len(blocked)} blocked, "
      f"{len(fails)} non-compiling sources: {' '.join(sorted(fails))}",
      file=sys.stderr)
